mode:
    production

production:
    datasources:
        mysql:
            disable: true
        mongodb:
           disable: true
        redis:
           disable: true

test:
    datasources:
        mysql:
           disable: true
        mongodb:
           disable: true

application:
    controllerNames: streaming.rest.RestController,streaming.king.rest.MetaController
    service:
    util:
    test:
    static:
        enable: true
    template:
        engine:
           enable: true

serviceframework:
    template:
        loader:
             classpath:
                  enable: true
    static:
        loader:
             classpath:
                  enable: true
                  dir: "streamingpro/assets"
###############http config##################
http:
    port: 9003
    disable: false
thrift:
    disable: true
dubbo:
    disable: true

es:
    nodes: 10.148.16.50:9200
    resource: test_db_rest/rest



